# coding: utf-8

"""
    Deep Search (DS) API

    API for Deep Search.  **WARNING**: This API is subject to change without warning!

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class StatusFilter(str, Enum):
    """
    StatusFilter
    """

    """
    allowed enum values
    """
    PENDING = 'PENDING'
    FAILURE = 'FAILURE'
    SUCCESS = 'SUCCESS'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of StatusFilter from a JSON string"""
        return cls(json.loads(json_str))


