# coding: utf-8

"""
    User Management API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from deepsearch.cps.apis.user.configuration import Configuration


class ImpersonateUserTokenRequestBody(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'impersonate_secret': 'str',
        'target_user_key': 'str'
    }

    attribute_map = {
        'impersonate_secret': 'impersonate_secret',
        'target_user_key': 'target_user_key'
    }

    def __init__(self, impersonate_secret=None, target_user_key=None, local_vars_configuration=None):  # noqa: E501
        """ImpersonateUserTokenRequestBody - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._impersonate_secret = None
        self._target_user_key = None
        self.discriminator = None

        self.impersonate_secret = impersonate_secret
        self.target_user_key = target_user_key

    @property
    def impersonate_secret(self):
        """Gets the impersonate_secret of this ImpersonateUserTokenRequestBody.  # noqa: E501


        :return: The impersonate_secret of this ImpersonateUserTokenRequestBody.  # noqa: E501
        :rtype: str
        """
        return self._impersonate_secret

    @impersonate_secret.setter
    def impersonate_secret(self, impersonate_secret):
        """Sets the impersonate_secret of this ImpersonateUserTokenRequestBody.


        :param impersonate_secret: The impersonate_secret of this ImpersonateUserTokenRequestBody.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and impersonate_secret is None:  # noqa: E501
            raise ValueError("Invalid value for `impersonate_secret`, must not be `None`")  # noqa: E501

        self._impersonate_secret = impersonate_secret

    @property
    def target_user_key(self):
        """Gets the target_user_key of this ImpersonateUserTokenRequestBody.  # noqa: E501


        :return: The target_user_key of this ImpersonateUserTokenRequestBody.  # noqa: E501
        :rtype: str
        """
        return self._target_user_key

    @target_user_key.setter
    def target_user_key(self, target_user_key):
        """Sets the target_user_key of this ImpersonateUserTokenRequestBody.


        :param target_user_key: The target_user_key of this ImpersonateUserTokenRequestBody.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and target_user_key is None:  # noqa: E501
            raise ValueError("Invalid value for `target_user_key`, must not be `None`")  # noqa: E501

        self._target_user_key = target_user_key

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ImpersonateUserTokenRequestBody):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ImpersonateUserTokenRequestBody):
            return True

        return self.to_dict() != other.to_dict()
