name: 'Checkout and install'
description: 'Checkout a repository and install with Poetry'
inputs:
  python-version:
    description: "Version range or exact version of Python or PyPy to use, using SemVer's version range syntax. Reads from .python-version if unset."
    default: '3.x'
  poetry-spec:
    description: 'Spec for installation of Poetry'
    default: '1.2.*'
runs:
  using: 'composite'
  steps:
    - name: Install poetry
      run: pipx install 'poetry==${{ inputs.poetry-spec }}'
      shell: bash
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'poetry'
    - name: Install dependencies
      run: poetry install
      shell: bash
