# coding: utf-8

"""
    Corpus Processing Service (CPS) API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from deepsearch.cps.apis.public.configuration import Configuration


class Bag(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'svc_endpoint': 'str',
        'bag_domain': 'str',
        'bag_key': 'str',
        'bag_url': 'str',
        'flavour': 'str',
        'name': 'str',
        'proj_key': 'str',
        'public': 'bool',
        'slug': 'str',
        'timestamp': 'float',
        'token': 'str'
    }

    attribute_map = {
        'svc_endpoint': '_svc_endpoint',
        'bag_domain': 'bag_domain',
        'bag_key': 'bag_key',
        'bag_url': 'bag_url',
        'flavour': 'flavour',
        'name': 'name',
        'proj_key': 'proj_key',
        'public': 'public',
        'slug': 'slug',
        'timestamp': 'timestamp',
        'token': 'token'
    }

    def __init__(self, svc_endpoint=None, bag_domain=None, bag_key=None, bag_url=None, flavour=None, name=None, proj_key=None, public=None, slug=None, timestamp=None, token=None, local_vars_configuration=None):  # noqa: E501
        """Bag - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._svc_endpoint = None
        self._bag_domain = None
        self._bag_key = None
        self._bag_url = None
        self._flavour = None
        self._name = None
        self._proj_key = None
        self._public = None
        self._slug = None
        self._timestamp = None
        self._token = None
        self.discriminator = None

        self.svc_endpoint = svc_endpoint
        self.bag_domain = bag_domain
        self.bag_key = bag_key
        self.bag_url = bag_url
        self.flavour = flavour
        self.name = name
        self.proj_key = proj_key
        self.public = public
        self.slug = slug
        self.timestamp = timestamp
        self.token = token

    @property
    def svc_endpoint(self):
        """Gets the svc_endpoint of this Bag.  # noqa: E501


        :return: The svc_endpoint of this Bag.  # noqa: E501
        :rtype: str
        """
        return self._svc_endpoint

    @svc_endpoint.setter
    def svc_endpoint(self, svc_endpoint):
        """Sets the svc_endpoint of this Bag.


        :param svc_endpoint: The svc_endpoint of this Bag.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and svc_endpoint is None:  # noqa: E501
            raise ValueError("Invalid value for `svc_endpoint`, must not be `None`")  # noqa: E501

        self._svc_endpoint = svc_endpoint

    @property
    def bag_domain(self):
        """Gets the bag_domain of this Bag.  # noqa: E501


        :return: The bag_domain of this Bag.  # noqa: E501
        :rtype: str
        """
        return self._bag_domain

    @bag_domain.setter
    def bag_domain(self, bag_domain):
        """Sets the bag_domain of this Bag.


        :param bag_domain: The bag_domain of this Bag.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and bag_domain is None:  # noqa: E501
            raise ValueError("Invalid value for `bag_domain`, must not be `None`")  # noqa: E501

        self._bag_domain = bag_domain

    @property
    def bag_key(self):
        """Gets the bag_key of this Bag.  # noqa: E501


        :return: The bag_key of this Bag.  # noqa: E501
        :rtype: str
        """
        return self._bag_key

    @bag_key.setter
    def bag_key(self, bag_key):
        """Sets the bag_key of this Bag.


        :param bag_key: The bag_key of this Bag.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and bag_key is None:  # noqa: E501
            raise ValueError("Invalid value for `bag_key`, must not be `None`")  # noqa: E501

        self._bag_key = bag_key

    @property
    def bag_url(self):
        """Gets the bag_url of this Bag.  # noqa: E501


        :return: The bag_url of this Bag.  # noqa: E501
        :rtype: str
        """
        return self._bag_url

    @bag_url.setter
    def bag_url(self, bag_url):
        """Sets the bag_url of this Bag.


        :param bag_url: The bag_url of this Bag.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and bag_url is None:  # noqa: E501
            raise ValueError("Invalid value for `bag_url`, must not be `None`")  # noqa: E501

        self._bag_url = bag_url

    @property
    def flavour(self):
        """Gets the flavour of this Bag.  # noqa: E501


        :return: The flavour of this Bag.  # noqa: E501
        :rtype: str
        """
        return self._flavour

    @flavour.setter
    def flavour(self, flavour):
        """Sets the flavour of this Bag.


        :param flavour: The flavour of this Bag.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and flavour is None:  # noqa: E501
            raise ValueError("Invalid value for `flavour`, must not be `None`")  # noqa: E501

        self._flavour = flavour

    @property
    def name(self):
        """Gets the name of this Bag.  # noqa: E501


        :return: The name of this Bag.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Bag.


        :param name: The name of this Bag.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and name is None:  # noqa: E501
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def proj_key(self):
        """Gets the proj_key of this Bag.  # noqa: E501


        :return: The proj_key of this Bag.  # noqa: E501
        :rtype: str
        """
        return self._proj_key

    @proj_key.setter
    def proj_key(self, proj_key):
        """Sets the proj_key of this Bag.


        :param proj_key: The proj_key of this Bag.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and proj_key is None:  # noqa: E501
            raise ValueError("Invalid value for `proj_key`, must not be `None`")  # noqa: E501

        self._proj_key = proj_key

    @property
    def public(self):
        """Gets the public of this Bag.  # noqa: E501


        :return: The public of this Bag.  # noqa: E501
        :rtype: bool
        """
        return self._public

    @public.setter
    def public(self, public):
        """Sets the public of this Bag.


        :param public: The public of this Bag.  # noqa: E501
        :type: bool
        """
        if self.local_vars_configuration.client_side_validation and public is None:  # noqa: E501
            raise ValueError("Invalid value for `public`, must not be `None`")  # noqa: E501

        self._public = public

    @property
    def slug(self):
        """Gets the slug of this Bag.  # noqa: E501


        :return: The slug of this Bag.  # noqa: E501
        :rtype: str
        """
        return self._slug

    @slug.setter
    def slug(self, slug):
        """Sets the slug of this Bag.


        :param slug: The slug of this Bag.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and slug is None:  # noqa: E501
            raise ValueError("Invalid value for `slug`, must not be `None`")  # noqa: E501

        self._slug = slug

    @property
    def timestamp(self):
        """Gets the timestamp of this Bag.  # noqa: E501


        :return: The timestamp of this Bag.  # noqa: E501
        :rtype: float
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this Bag.


        :param timestamp: The timestamp of this Bag.  # noqa: E501
        :type: float
        """
        if self.local_vars_configuration.client_side_validation and timestamp is None:  # noqa: E501
            raise ValueError("Invalid value for `timestamp`, must not be `None`")  # noqa: E501

        self._timestamp = timestamp

    @property
    def token(self):
        """Gets the token of this Bag.  # noqa: E501


        :return: The token of this Bag.  # noqa: E501
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token):
        """Sets the token of this Bag.


        :param token: The token of this Bag.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and token is None:  # noqa: E501
            raise ValueError("Invalid value for `token`, must not be `None`")  # noqa: E501

        self._token = token

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Bag):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Bag):
            return True

        return self.to_dict() != other.to_dict()
