# coding: utf-8

"""
    Corpus Processing Service (CPS) API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from deepsearch.cps.apis.public.configuration import Configuration


class DataFlowAssembleReportSingleTask(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'chunks': 'DataFlowAssembleReportChunks',
        'errors': 'list[DataFlowAssembleReportErrors]',
        'progress': 'float',
        'status': 'str',
        'task_type': 'str'
    }

    attribute_map = {
        'chunks': 'chunks',
        'errors': 'errors',
        'progress': 'progress',
        'status': 'status',
        'task_type': 'task_type'
    }

    def __init__(self, chunks=None, errors=None, progress=None, status=None, task_type=None, local_vars_configuration=None):  # noqa: E501
        """DataFlowAssembleReportSingleTask - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._chunks = None
        self._errors = None
        self._progress = None
        self._status = None
        self._task_type = None
        self.discriminator = None

        if chunks is not None:
            self.chunks = chunks
        if errors is not None:
            self.errors = errors
        if progress is not None:
            self.progress = progress
        if status is not None:
            self.status = status
        if task_type is not None:
            self.task_type = task_type

    @property
    def chunks(self):
        """Gets the chunks of this DataFlowAssembleReportSingleTask.  # noqa: E501


        :return: The chunks of this DataFlowAssembleReportSingleTask.  # noqa: E501
        :rtype: DataFlowAssembleReportChunks
        """
        return self._chunks

    @chunks.setter
    def chunks(self, chunks):
        """Sets the chunks of this DataFlowAssembleReportSingleTask.


        :param chunks: The chunks of this DataFlowAssembleReportSingleTask.  # noqa: E501
        :type: DataFlowAssembleReportChunks
        """

        self._chunks = chunks

    @property
    def errors(self):
        """Gets the errors of this DataFlowAssembleReportSingleTask.  # noqa: E501


        :return: The errors of this DataFlowAssembleReportSingleTask.  # noqa: E501
        :rtype: list[DataFlowAssembleReportErrors]
        """
        return self._errors

    @errors.setter
    def errors(self, errors):
        """Sets the errors of this DataFlowAssembleReportSingleTask.


        :param errors: The errors of this DataFlowAssembleReportSingleTask.  # noqa: E501
        :type: list[DataFlowAssembleReportErrors]
        """

        self._errors = errors

    @property
    def progress(self):
        """Gets the progress of this DataFlowAssembleReportSingleTask.  # noqa: E501


        :return: The progress of this DataFlowAssembleReportSingleTask.  # noqa: E501
        :rtype: float
        """
        return self._progress

    @progress.setter
    def progress(self, progress):
        """Sets the progress of this DataFlowAssembleReportSingleTask.


        :param progress: The progress of this DataFlowAssembleReportSingleTask.  # noqa: E501
        :type: float
        """

        self._progress = progress

    @property
    def status(self):
        """Gets the status of this DataFlowAssembleReportSingleTask.  # noqa: E501


        :return: The status of this DataFlowAssembleReportSingleTask.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this DataFlowAssembleReportSingleTask.


        :param status: The status of this DataFlowAssembleReportSingleTask.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def task_type(self):
        """Gets the task_type of this DataFlowAssembleReportSingleTask.  # noqa: E501


        :return: The task_type of this DataFlowAssembleReportSingleTask.  # noqa: E501
        :rtype: str
        """
        return self._task_type

    @task_type.setter
    def task_type(self, task_type):
        """Sets the task_type of this DataFlowAssembleReportSingleTask.


        :param task_type: The task_type of this DataFlowAssembleReportSingleTask.  # noqa: E501
        :type: str
        """

        self._task_type = task_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DataFlowAssembleReportSingleTask):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, DataFlowAssembleReportSingleTask):
            return True

        return self.to_dict() != other.to_dict()
