# coding: utf-8

"""
    Corpus Processing Service (CPS) API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from deepsearch.cps.apis.public.configuration import Configuration


class DataFlowAssembleReportErrors(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'cause': 'DataFlowAssembleReportCause',
        'timestamp': 'float'
    }

    attribute_map = {
        'cause': 'cause',
        'timestamp': 'timestamp'
    }

    def __init__(self, cause=None, timestamp=None, local_vars_configuration=None):  # noqa: E501
        """DataFlowAssembleReportErrors - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._cause = None
        self._timestamp = None
        self.discriminator = None

        if cause is not None:
            self.cause = cause
        if timestamp is not None:
            self.timestamp = timestamp

    @property
    def cause(self):
        """Gets the cause of this DataFlowAssembleReportErrors.  # noqa: E501


        :return: The cause of this DataFlowAssembleReportErrors.  # noqa: E501
        :rtype: DataFlowAssembleReportCause
        """
        return self._cause

    @cause.setter
    def cause(self, cause):
        """Sets the cause of this DataFlowAssembleReportErrors.


        :param cause: The cause of this DataFlowAssembleReportErrors.  # noqa: E501
        :type: DataFlowAssembleReportCause
        """

        self._cause = cause

    @property
    def timestamp(self):
        """Gets the timestamp of this DataFlowAssembleReportErrors.  # noqa: E501


        :return: The timestamp of this DataFlowAssembleReportErrors.  # noqa: E501
        :rtype: float
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this DataFlowAssembleReportErrors.


        :param timestamp: The timestamp of this DataFlowAssembleReportErrors.  # noqa: E501
        :type: float
        """

        self._timestamp = timestamp

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DataFlowAssembleReportErrors):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, DataFlowAssembleReportErrors):
            return True

        return self.to_dict() != other.to_dict()
