# coding: utf-8

"""
    Corpus Processing Service (CPS) API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from deepsearch.cps.apis.public.configuration import Configuration


class ProjectDataIndexView(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'description': 'str',
        'name': 'str',
        'view_of': 'ProjectDataIndexViewOf'
    }

    attribute_map = {
        'description': 'description',
        'name': 'name',
        'view_of': 'view_of'
    }

    def __init__(self, description=None, name=None, view_of=None, local_vars_configuration=None):  # noqa: E501
        """ProjectDataIndexView - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._description = None
        self._name = None
        self._view_of = None
        self.discriminator = None

        if description is not None:
            self.description = description
        self.name = name
        self.view_of = view_of

    @property
    def description(self):
        """Gets the description of this ProjectDataIndexView.  # noqa: E501

        Description of the index view  # noqa: E501

        :return: The description of this ProjectDataIndexView.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this ProjectDataIndexView.

        Description of the index view  # noqa: E501

        :param description: The description of this ProjectDataIndexView.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                description is not None and len(description) > 254):
            raise ValueError("Invalid value for `description`, length must be less than or equal to `254`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                description is not None and len(description) < 1):
            raise ValueError("Invalid value for `description`, length must be greater than or equal to `1`")  # noqa: E501

        self._description = description

    @property
    def name(self):
        """Gets the name of this ProjectDataIndexView.  # noqa: E501

        Name of the data index view  # noqa: E501

        :return: The name of this ProjectDataIndexView.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ProjectDataIndexView.

        Name of the data index view  # noqa: E501

        :param name: The name of this ProjectDataIndexView.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and name is None:  # noqa: E501
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                name is not None and len(name) > 64):
            raise ValueError("Invalid value for `name`, length must be less than or equal to `64`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                name is not None and len(name) < 1):
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")  # noqa: E501

        self._name = name

    @property
    def view_of(self):
        """Gets the view_of of this ProjectDataIndexView.  # noqa: E501


        :return: The view_of of this ProjectDataIndexView.  # noqa: E501
        :rtype: ProjectDataIndexViewOf
        """
        return self._view_of

    @view_of.setter
    def view_of(self, view_of):
        """Sets the view_of of this ProjectDataIndexView.


        :param view_of: The view_of of this ProjectDataIndexView.  # noqa: E501
        :type: ProjectDataIndexViewOf
        """
        if self.local_vars_configuration.client_side_validation and view_of is None:  # noqa: E501
            raise ValueError("Invalid value for `view_of`, must not be `None`")  # noqa: E501

        self._view_of = view_of

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProjectDataIndexView):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ProjectDataIndexView):
            return True

        return self.to_dict() != other.to_dict()
