# coding: utf-8

"""
    Corpus Processing Service (CPS) API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from deepsearch.cps.apis.public.configuration import Configuration


class SuspendKnowledgeGraphOptions(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'force': 'bool',
        'snapshot': 'ProjectProjKeyBagsBagKeyTasksSuspendSnapshot'
    }

    attribute_map = {
        'force': 'force',
        'snapshot': 'snapshot'
    }

    def __init__(self, force=None, snapshot=None, local_vars_configuration=None):  # noqa: E501
        """SuspendKnowledgeGraphOptions - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._force = None
        self._snapshot = None
        self.discriminator = None

        self.force = force
        if snapshot is not None:
            self.snapshot = snapshot

    @property
    def force(self):
        """Gets the force of this SuspendKnowledgeGraphOptions.  # noqa: E501

        If true, the KG will be suspended even if it's busy  # noqa: E501

        :return: The force of this SuspendKnowledgeGraphOptions.  # noqa: E501
        :rtype: bool
        """
        return self._force

    @force.setter
    def force(self, force):
        """Sets the force of this SuspendKnowledgeGraphOptions.

        If true, the KG will be suspended even if it's busy  # noqa: E501

        :param force: The force of this SuspendKnowledgeGraphOptions.  # noqa: E501
        :type: bool
        """
        if self.local_vars_configuration.client_side_validation and force is None:  # noqa: E501
            raise ValueError("Invalid value for `force`, must not be `None`")  # noqa: E501

        self._force = force

    @property
    def snapshot(self):
        """Gets the snapshot of this SuspendKnowledgeGraphOptions.  # noqa: E501


        :return: The snapshot of this SuspendKnowledgeGraphOptions.  # noqa: E501
        :rtype: ProjectProjKeyBagsBagKeyTasksSuspendSnapshot
        """
        return self._snapshot

    @snapshot.setter
    def snapshot(self, snapshot):
        """Sets the snapshot of this SuspendKnowledgeGraphOptions.


        :param snapshot: The snapshot of this SuspendKnowledgeGraphOptions.  # noqa: E501
        :type: ProjectProjKeyBagsBagKeyTasksSuspendSnapshot
        """

        self._snapshot = snapshot

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SuspendKnowledgeGraphOptions):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, SuspendKnowledgeGraphOptions):
            return True

        return self.to_dict() != other.to_dict()
