# coding: utf-8

"""
    Corpus Processing Service (CPS) API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from deepsearch.cps.apis.public.configuration import Configuration


class SystemInfoDeploymentLinkedCcsApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'project_sync': 'bool',
        'uri': 'str'
    }

    attribute_map = {
        'project_sync': 'project_sync',
        'uri': 'uri'
    }

    def __init__(self, project_sync=None, uri=None, local_vars_configuration=None):  # noqa: E501
        """SystemInfoDeploymentLinkedCcsApi - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._project_sync = None
        self._uri = None
        self.discriminator = None

        if project_sync is not None:
            self.project_sync = project_sync
        if uri is not None:
            self.uri = uri

    @property
    def project_sync(self):
        """Gets the project_sync of this SystemInfoDeploymentLinkedCcsApi.  # noqa: E501


        :return: The project_sync of this SystemInfoDeploymentLinkedCcsApi.  # noqa: E501
        :rtype: bool
        """
        return self._project_sync

    @project_sync.setter
    def project_sync(self, project_sync):
        """Sets the project_sync of this SystemInfoDeploymentLinkedCcsApi.


        :param project_sync: The project_sync of this SystemInfoDeploymentLinkedCcsApi.  # noqa: E501
        :type: bool
        """

        self._project_sync = project_sync

    @property
    def uri(self):
        """Gets the uri of this SystemInfoDeploymentLinkedCcsApi.  # noqa: E501


        :return: The uri of this SystemInfoDeploymentLinkedCcsApi.  # noqa: E501
        :rtype: str
        """
        return self._uri

    @uri.setter
    def uri(self, uri):
        """Sets the uri of this SystemInfoDeploymentLinkedCcsApi.


        :param uri: The uri of this SystemInfoDeploymentLinkedCcsApi.  # noqa: E501
        :type: str
        """

        self._uri = uri

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SystemInfoDeploymentLinkedCcsApi):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, SystemInfoDeploymentLinkedCcsApi):
            return True

        return self.to_dict() != other.to_dict()
