# coding: utf-8

# flake8: noqa
"""
    Knowledge-Graph Create API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
from deepsearch.cps.apis.kg.create.models.database_source import DatabaseSource
from deepsearch.cps.apis.kg.create.models.database_source_mongo import DatabaseSourceMongo
from deepsearch.cps.apis.kg.create.models.database_source_s3 import DatabaseSourceS3
from deepsearch.cps.apis.kg.create.models.edge_matrix import EdgeMatrix
from deepsearch.cps.apis.kg.create.models.edge_model import EdgeModel
from deepsearch.cps.apis.kg.create.models.inline_object import InlineObject
from deepsearch.cps.apis.kg.create.models.inline_object1 import InlineObject1
from deepsearch.cps.apis.kg.create.models.inline_object2 import InlineObject2
from deepsearch.cps.apis.kg.create.models.mongo_edge import MongoEdge
from deepsearch.cps.apis.kg.create.models.mongo_edge_item import MongoEdgeItem
from deepsearch.cps.apis.kg.create.models.node import Node
from deepsearch.cps.apis.kg.create.models.s3_source import S3Source
from deepsearch.cps.apis.kg.create.models.sparse_matrix_with_names_or_hashes import SparseMatrixWithNamesOrHashes
from deepsearch.cps.apis.kg.create.models.triplet import Triplet
