name: "Bump version, build, and release"

on:
  push:
    branches:
      - main

env:
  # disable keyring (https://github.com/actions/runner-images/issues/6185):
  PYTHON_KEYRING_BACKEND: keyring.backends.null.Keyring

jobs:
  docs:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
          cache: 'pip'
          cache-dependency-path: 'poetry.lock'
      - name: Install dependencies
        run: poetry install
      # - name: Build and push docs  # FIXME: revert
      #   run: poetry run mkdocs gh-deploy --force  # FIXME: revert
  release:
    environment: production
    runs-on: ubuntu-latest
    concurrency: release
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
          cache: 'pip'
          cache-dependency-path: 'poetry.lock'
      - name: Install dependencies
        run: poetry install
      - name: Run release script
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: ./.github/scripts/release.sh
        shell: bash
